// authentication
export const SET_LAT = 'SET_LAT'
export const SET_AUTH_REQUIRED = 'SET_AUTH_REQUIRED'
export const SET_FIELD = 'SET_FIELD'

//heatmap
export const GET_HEATMAPDATA_SUCCESS = 'GET_HEATMAPDATA_SUCCESS'
export const GET_TAXIZONES_SUCCESS='GET_TAXIZONES_SUCCESS'
export const GET_DASHBOARD_SUCCESS_Yellow = 'GET_DASHBOARD_SUCCESS_Yellow'
export const GET_DASHBOARD_SUCCESS_Green = 'GET_DASHBOARD_SUCCESS_Green'
export const UPDATE_SEARCH_ACTION='UPDATE_SEARCH_ACTION'
export const GET_LOCATIONDETAIL_SUCCESS='GET_LOCATIONDETAIL_SUCCESS'
export const GET_BARCHART_SUCCESS='GET_BARCHART_SUCCESS'